### ISSUE TITLE
How to upload a PyTorch model with Giskard?

### ISSUE THREAD

**Issue by jmsquare** [Giskard-AI/community-content#38]

**Comment by fakela** [comment]
Hi 👋, I'm interested in this topic

**Comment by alexcombessie** [comment]
Awesome! @jmsquare did you have an idea of a dataset / use case?

**Comment by fakela** [comment]
> Awesome! @jmsquare did you have an idea of a dataset / use case?

That would be great, if you have any idea of a dataset I could use for the tutorial

**Comment by jmsquare** [comment]
Hi @fakela, yes I'll send it to you!

**Comment by fakela** [comment]
Here is an update on the article: https://docs.google.com/document/d/15c5pdTNPg85UO1tWF4QHZrr0pBt5k3P5RXHF24w6sAU/edit#

**Comment by jmsquare** [comment]
Thank you very much Flavour for this great work !

Can you tell me where you define the def function "prediction_function"
that you uploaded in Giskard (your last code snippet on the Fine-tuned
model)

Thanks !

Le mar. 3 janv. 2023, 1:59 AM, Favour Kelvin ***@***.***> a
écrit :

**Comment by fakela** [comment]
> 

I have updated the code in the docs to show it.

**Comment by jmsquare** [comment]
Thank you!

Can you send me the colab link so that I can check if the model uploads to
Giskard.

This is a very good work!




Le mar. 3 janv. 2023, 11:37 PM, Favour Kelvin ***@***.***> a
écrit :

**Comment by fakela** [comment]
I made changes to the model I used initially, I have updated the docs to show that change.

Also here is a colab notebook: https://colab.research.google.com/drive/1IxEHrCHuvHKbbFIYKu1ZVt8rlTrLPVkg?usp=sharing

**Comment by fakela** [comment]
@jmsquare do let me know if you have further questions. Thanks

**Comment by alexcombessie** [comment]
Closed with https://www.giskard.ai/knowledge/how-to-evaluate-and-load-a-pytorch-model-with-giskard

Thanks @fakela for your great contribution!
